version: '3'
services:
  plasm:
    container_name: plasm
    hostname: plasm
    command: /opt/plasm --validator --name "rafael" --rpc-cors all
    build: /data/plasm/build
    volumes:
       - /data/plasm/root/.local:/root/.local
