version: '3'
services:
  plasm:
    container_name: plasm
    hostname: plasm
    command: /opt/plasm --validator --name "rafael" --rpc-cors all
    build: ./
    ports:
       - "443:443"
    volumes:
       - ./root/:/root/
